name: Trigger auto deployment for container-app-7irqbsjk5d652

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-7irqbsjk5d652-AutoDeployTrigger-144a0bd5-e249-4041-8bf4-9c81908d3944.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP7IRQBSJK5D652_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP7IRQBSJK5D652_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP7IRQBSJK5D652_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP7IRQBSJK5D652_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP7IRQBSJK5D652_REGISTRY_PASSWORD }}
          containerAppName: container-app-7irqbsjk5d652
          resourceGroup: todonodejspgsqlgoogleautha3fcb053
          imageToBuild: default/container-app-7irqbsjk5d652:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


